from flask import Blueprint, jsonify, request


risk_bp = Blueprint(
    "risk",
    __name__,
    url_prefix="/api/risk"
)


@risk_bp.route("/summary", methods=["GET"])
def risk_summary():
    """
    Returns overall traffic-risk information for Nagpur.
    """

    return jsonify({
        "success": True,
        "data": {
            "overall_risk": "Low",
            "risk_score": 0,
            "high_risk_zones": 0,
            "medium_risk_zones": 0,
            "low_risk_zones": 0
        }
    })


@risk_bp.route("/zones", methods=["GET"])
def risk_zones():
    """
    Returns risk information for different Nagpur locations.

    This will later be generated by the ML risk model.
    """

    return jsonify({
        "success": True,
        "location": "Nagpur",
        "zones": []
    })


@risk_bp.route("/ranking", methods=["GET"])
def risk_ranking():
    """
    Returns locations ranked according to traffic risk.
    """

    return jsonify({
        "success": True,
        "ranking": []
    })


@risk_bp.route("/predict", methods=["POST"])
def predict_risk():
    """
    Receives traffic/incident information and returns
    a risk prediction.

    The actual ML model will be connected later.
    """

    data = request.get_json(silent=True)

    if not data:
        return jsonify({
            "success": False,
            "message": "No input data provided"
        }), 400

    return jsonify({
        "success": True,
        "message": "Risk prediction endpoint is working",
        "prediction": {
            "risk_level": "Low",
            "risk_score": 0
        },
        "input": data
    })
